#Redis specific configurations
server:
  port: 8081
spring:
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
    database: 1
    redisson:
      url:redis://127.0.0.1:6379
  cache:
    redis:
      cache-null-values: false
      time-to-live: 600000ms
      use-key-prefix: true
    type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&useAffectedRows=true
    data-username: root
    password:
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
        format_sql: true

    show-sql: true
